---
label: Config
hide_body: true
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: Site title
    config:
      required: true
  - type: text
    name: baseURL
    label: Base URL
    description: Hostname (and path) to the root
    hidden: true
  - type: field_group
    name: params
    label: Params
    description: Site parameters
    config:
      required: true
    fields:
      - type: select
        name: palette
        label: Color Palette
        default: blue
        config:
          required: true
          source:
            type: custom
          options:
            - blue
            - cyan
            - green
            - red
      - type: field_group
        name: palettes
        label: Palettes
        hidden: true
        fields:
          - type: field_group
            name: blue
            label: Blue
            fields:
              - type: include
                name: include_palette
                label: Palette
                template: palette
          - type: field_group
            name: cyan
            label: Cyan
            fields:
              - type: include
                name: include_palette
                label: Palette
                template: palette
          - type: field_group
            name: green
            label: Green
            fields:
              - type: include
                name: include_palette
                label: Palette
                template: palette
          - type: field_group
            name: red
            label: Red
            fields:
              - type: include
                name: include_palette
                label: Palette
                template: palette
  - type: list
    name: disableKinds
    label: Disable Kinds
    description: Enable disabling of all pages of the specified Kinds.
    hidden: true
    config:
      source:
        type: custom
      options:
        - page
        - home
        - section
        - taxonomy
        - taxonomyTerm
        - RSS
        - sitemap
        - robotsTXT
        - '404'
      use_select: true
  - type: boolean
    name: uglyURLs
    label: Ugly URLs
    description: >-
      When enabled, creates URL of the form /filename.html instead of
      /filename/.
    hidden: true
